version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: patient_portal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: patient_portal
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
